# Ejemplo carga de archivos a Python con diferentes formatos


Introducción panorámica al proceso de ingestión de datos en pandas. Se muestra cómo un mismo conjunto de información puede residir en varios contenedores (texto plano, marcado, binario) y qué ajustes de lectura necesita cada uno para lograr un DataFrame coherente y bien tipado.

## Formato .csv

Texto plano delimitado por comas, ligero y casi universal: ideal para intercambios rápidos de datos tabulares. Requiere definir separador, codificación y, si hay comas embebidas, reglas de comillas y escape. Es el “lenguaje franca” entre hojas de cálculo, bases de datos y scripts.

In [8]:
import pandas as pd

data_csv = pd.read_csv('data_load/mtcars.csv')

data_csv.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## Formato .tsv

Variante del CSV que usa tabulaciones como separador; minimiza choques con valores que ya incluyen comas. Muy apreciado en bioinformática y entornos UNIX. Basta indicar `sep='\t'` en `read_csv` — el resto se comporta igual que un CSV.

In [9]:
data_tsv = pd.read_csv('data_load/mtcars.tsv', sep='\t')

data_tsv.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## Formato .json

Estructura jerárquica de pares clave-valor, perfecta para datos anidados o provenientes de API web. Pandas detecta listas y diccionarios y los “aplana” según corresponda; permite conservar la semántica original (objetos, arrays) que no cabe en una tabla CSV tradicional.

In [10]:
data_json = pd.read_json('data_load/mtcars.json')

data_json.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## Formato .xml

Lenguaje de marcado con etiquetas auto-descriptivas, habitual en servicios antiguos y especificaciones de industria. Su jerarquía exige un parser (por ejemplo, lxml) y, al leerlo, es crucial apuntar a la profundidad (xpath) correcta para convertir nodos repetidos en filas de un DataFrame.

In [11]:
# Requires installation of lxml library

data_xml = pd.read_xml('data_load/mtcars.xml')

data_xml.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## Formato .xlsx

Contenedor binario (en realidad un ZIP con XML interno) que soporta múltiples hojas, fórmulas y tipos ricos como fechas. Con `read_excel` y motores como *openpyxl* puedes traer una o varias hojas, elegir rangos y controlar las cabeceras. Es la mejor opción cuando el archivo proviene directamente de usuarios de Excel y se necesita mantener metadatos de celdas.

In [13]:
# Requires installation of openpyxl library

data_excel = pd.read_excel('data_load/mtcars.xlsx')

data_excel.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2